version: "3"
services:
  28car-crawler:
    image: 28car-crawler
    networks:
      - 28car
    depends_on:
      - mongo
      - redis
    environment:
      - redis=redis:6379
      - mongo=mongo:27017
    deploy:
      placement:
        constraints: [node.role == manager]
  mongo:
    image: mongo:latest
    networks:
      - 28car
    volumes:
      - $HOME/data/mongo:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  redis:
    image: redis:latest
    networks:
      - 28car
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
networks:
  28car: